// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// @version=6
indicator("Weekly Monthly Highs & Lows", "WM HL", true)

//--------------------------------------------------------------------
//                        Variables declarations
//--------------------------------------------------------------------
var float prevWeeklyHigh  = na
var float prevWeeklyLow   = na
var float prevMonthlyHigh = na
var float prevMonthlyLow  = na

[weeklyTime,  weeklyHigh,  weeklyLow,  isLastWeekly]  = request.security(syminfo.tickerid, 'W', [time, high, low, barstate.islast], lookahead=barmerge.lookahead_on)
[monthlyTime, monthlyHigh, monthlyLow, isLastMonthly] = request.security(syminfo.tickerid, 'M', [time, high, low, barstate.islast], lookahead=barmerge.lookahead_on)

//--------------------------------------------------------------------
//                                Logic
//--------------------------------------------------------------------
if weeklyTime != weeklyTime[1] and not isLastWeekly
    prevWeeklyHigh := weeklyHigh
    prevWeeklyLow  := weeklyLow

if monthlyTime != monthlyTime[1] and not isLastMonthly
    prevMonthlyHigh := monthlyHigh
    prevMonthlyLow  := monthlyLow

//--------------------------------------------------------------------
//                               Plots
//--------------------------------------------------------------------
plot(close,           "Price", display=display.data_window + display.status_line)
plot(prevWeeklyHigh,  "WH",    display=display.data_window + display.status_line)
plot(prevWeeklyLow,   "WL",    display=display.data_window + display.status_line)
plot(prevMonthlyHigh, "MH",    display=display.data_window + display.status_line)
plot(prevMonthlyLow,  "ML",    display=display.data_window + display.status_line)
